package com.beibei.erp.mapper;

import java.util.List;
import java.util.Map;

import com.beibei.erp.bean.Deliver;

public interface DeliverMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deliver
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	int deleteByPrimaryKey(Integer pk);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deliver
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	int insert(Deliver record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deliver
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	int insertSelective(Deliver record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deliver
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	Deliver selectByPrimaryKey(Integer pk);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deliver
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	int updateByPrimaryKeySelective(Deliver record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deliver
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	int updateByPrimaryKey(Deliver record);

	int insertHasDate(Deliver deliver);
    
    List<Deliver> selectAll();
    
    List<Deliver> selectByDate(Map<String,String> map);
}