package com.beibei.erp.mapper;

import java.util.List;

import com.beibei.erp.bean.Deliver;
import com.beibei.erp.bean.DeliverDetail;

public interface DeliverDetailMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deliver_detail
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	int deleteByPrimaryKey(Integer pk);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deliver_detail
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	int insert(DeliverDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deliver_detail
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	int insertSelective(DeliverDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deliver_detail
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	DeliverDetail selectByPrimaryKey(Integer pk);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deliver_detail
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	int updateByPrimaryKeySelective(DeliverDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table deliver_detail
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	int updateByPrimaryKey(DeliverDetail record);

	int insertAll(Deliver deliver);
    
    List<DeliverDetail> selectByDeliverid(String deliver_id);
}