package com.beibei.erp.mapper;

import java.util.List;

import com.beibei.erp.bean.ProductSupplier;

public interface ProductSupplierMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_supplier
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer pk);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_supplier
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	int insert(ProductSupplier record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_supplier
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	int insertSelective(ProductSupplier record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_supplier
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	ProductSupplier selectByPrimaryKey(Integer pk);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_supplier
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	int updateByPrimaryKeySelective(ProductSupplier record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_supplier
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	int updateByPrimaryKey(ProductSupplier record);
	
	List<ProductSupplier> selectByP_num(String p_num);
}