package com.beibei.erp.mapper;

import java.util.List;
import java.util.Map;

import com.beibei.erp.bean.ProductSupplier;

public interface ProductSupplierMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_supplier
	 * @mbggenerated  Sat Jul 04 21:09:29 CST 2015
	 */
	int deleteByPrimaryKey(Integer pk);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_supplier
	 * @mbggenerated  Sat Jul 04 21:09:29 CST 2015
	 */
	int insert(ProductSupplier record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_supplier
	 * @mbggenerated  Sat Jul 04 21:09:29 CST 2015
	 */
	int insertSelective(ProductSupplier record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_supplier
	 * @mbggenerated  Sat Jul 04 21:09:29 CST 2015
	 */
	ProductSupplier selectByPrimaryKey(Integer pk);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_supplier
	 * @mbggenerated  Sat Jul 04 21:09:29 CST 2015
	 */
	int updateByPrimaryKeySelective(ProductSupplier record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_supplier
	 * @mbggenerated  Sat Jul 04 21:09:29 CST 2015
	 */
	int updateByPrimaryKey(ProductSupplier record);

	List<ProductSupplier> selectByP_num(String p_num);
	
	List<ProductSupplier> selectBySupplierAndLike(Map<String,Object> map);
}