package com.beibei.erp.mapper;

import java.util.List;
import java.util.Map;

import com.beibei.erp.bean.Purchase;

public interface PurchaseMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase
	 * @mbggenerated  Sat Jul 04 21:09:29 CST 2015
	 */
	int deleteByPrimaryKey(Integer pk);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase
	 * @mbggenerated  Sat Jul 04 21:09:29 CST 2015
	 */
	int insert(Purchase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase
	 * @mbggenerated  Sat Jul 04 21:09:29 CST 2015
	 */
	int insertSelective(Purchase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase
	 * @mbggenerated  Sat Jul 04 21:09:29 CST 2015
	 */
	Purchase selectByPrimaryKey(Integer pk);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase
	 * @mbggenerated  Sat Jul 04 21:09:29 CST 2015
	 */
	int updateByPrimaryKeySelective(Purchase record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase
	 * @mbggenerated  Sat Jul 04 21:09:29 CST 2015
	 */
	int updateByPrimaryKey(Purchase record);

	int insertHasDate(Purchase record);
    
    List<Purchase> selectAll();
    
    List<Purchase> selectByDate(Map<String,String> map);
}