package com.beibei.erp.mapper;

import java.util.List;

import com.beibei.erp.bean.Purchase;
import com.beibei.erp.bean.PurchaseDetail;
import com.beibei.erp.bean.PurchaseDetailKey;

public interface PurchaseDetailMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_detail
	 * @mbggenerated  Sat Jul 04 21:09:29 CST 2015
	 */
	int deleteByPrimaryKey(Integer pk);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_detail
	 * @mbggenerated  Sat Jul 04 21:09:29 CST 2015
	 */
	int insert(PurchaseDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_detail
	 * @mbggenerated  Sat Jul 04 21:09:29 CST 2015
	 */
	int insertSelective(PurchaseDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_detail
	 * @mbggenerated  Sat Jul 04 21:09:29 CST 2015
	 */
	PurchaseDetail selectByPrimaryKey(Integer pk);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_detail
	 * @mbggenerated  Sat Jul 04 21:09:29 CST 2015
	 */
	int updateByPrimaryKeySelective(PurchaseDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table purchase_detail
	 * @mbggenerated  Sat Jul 04 21:09:29 CST 2015
	 */
	int updateByPrimaryKey(PurchaseDetail record);

	int insertAll(Purchase purchase);
    
    List<PurchaseDetail> selectByPurchaseid(String purchase_id);
}