package com.beibei.erp.mapper;

import java.util.List;

import com.beibei.erp.bean.Supplier;

public interface SupplierMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer pk);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	int insert(Supplier record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	int insertSelective(Supplier record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	Supplier selectByPrimaryKey(Integer pk);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	int updateByPrimaryKeySelective(Supplier record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table supplier
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	int updateByPrimaryKey(Supplier record);
	List<Supplier> selectAll();
    void deleteBatchByPk(List<String> list);
}