package com.beibei.erp.bean;

public class DeliverDetail {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliver_detail.pk
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private Integer pk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliver_detail.deliver_id
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private String deliver_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliver_detail.p_id
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private int p_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliver_detail.p_count_out
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private int p_count_out;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column deliver_detail.p_price
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private int p_price;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliver_detail.pk
	 * @return  the value of deliver_detail.pk
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public Integer getPk() {
		return pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliver_detail.pk
	 * @param pk  the value for deliver_detail.pk
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setPk(Integer pk) {
		this.pk = pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliver_detail.deliver_id
	 * @return  the value of deliver_detail.deliver_id
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public String getDeliver_id() {
		return deliver_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliver_detail.deliver_id
	 * @param deliver_id  the value for deliver_detail.deliver_id
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setDeliver_id(String deliver_id) {
		this.deliver_id = deliver_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliver_detail.p_id
	 * @return  the value of deliver_detail.p_id
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public int getP_id() {
		return p_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliver_detail.p_id
	 * @param p_id  the value for deliver_detail.p_id
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_id(int p_id) {
		this.p_id = p_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliver_detail.p_count_out
	 * @return  the value of deliver_detail.p_count_out
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public int getP_count_out() {
		return p_count_out;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliver_detail.p_count_out
	 * @param p_count_out  the value for deliver_detail.p_count_out
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_count_out(int p_count_out) {
		this.p_count_out = p_count_out;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column deliver_detail.p_price
	 * @return  the value of deliver_detail.p_price
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public int getP_price() {
		return p_price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column deliver_detail.p_price
	 * @param p_price  the value for deliver_detail.p_price
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_price(int p_price) {
		this.p_price = p_price;
	}

	private String p_num;
	private String p_name;
	private String jsonId;

	public String getP_num() {
		return p_num;
	}

	public void setP_num(String p_num) {
		this.p_num = p_num;
	}

	public String getP_name() {
		return p_name;
	}

	public void setP_name(String p_name) {
		this.p_name = p_name;
	}

	public String getJsonId() {
		return jsonId;
	}

	public void setJsonId(String jsonId) {
		this.jsonId = jsonId;
	}
	
	
}