package com.beibei.erp.bean;

public class ProductSupplier {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_supplier.pk
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	private Integer pk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_supplier.p_num
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	private String p_num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_supplier.supplier_id
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	private String supplier_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_supplier.supplier_p_num
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	private String supplier_p_num;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_supplier.pk
	 * @return  the value of product_supplier.pk
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public Integer getPk() {
		return pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_supplier.pk
	 * @param pk  the value for product_supplier.pk
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public void setPk(Integer pk) {
		this.pk = pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_supplier.p_num
	 * @return  the value of product_supplier.p_num
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public String getP_num() {
		return p_num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_supplier.p_num
	 * @param p_num  the value for product_supplier.p_num
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public void setP_num(String p_num) {
		this.p_num = p_num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_supplier.supplier_id
	 * @return  the value of product_supplier.supplier_id
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public String getSupplier_id() {
		return supplier_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_supplier.supplier_id
	 * @param supplier_id  the value for product_supplier.supplier_id
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public void setSupplier_id(String supplier_id) {
		this.supplier_id = supplier_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_supplier.supplier_p_num
	 * @return  the value of product_supplier.supplier_p_num
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public String getSupplier_p_num() {
		return supplier_p_num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_supplier.supplier_p_num
	 * @param supplier_p_num  the value for product_supplier.supplier_p_num
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public void setSupplier_p_num(String supplier_p_num) {
		this.supplier_p_num = supplier_p_num;
	}
}