package com.beibei.erp.bean;

public class ProductKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.p_id
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private int p_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.p_num
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private String p_num;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.p_id
	 * @return  the value of product.p_id
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public int getP_id() {
		return p_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.p_id
	 * @param p_id  the value for product.p_id
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_id(int p_id) {
		this.p_id = p_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.p_num
	 * @return  the value of product.p_num
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public String getP_num() {
		return p_num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.p_num
	 * @param p_num  the value for product.p_num
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_num(String p_num) {
		this.p_num = p_num;
	}
}