package com.beibei.erp.bean;

public class Product extends ProductKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.p_my_num
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private String p_my_num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.p_name
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private String p_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.p_abbreviation
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private String p_abbreviation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.p_barcode
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private String p_barcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.p_unit
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private String p_unit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.p_size
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private String p_size;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.p_class_id
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private int p_class_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.p_cost
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private double p_cost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.p_price
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private double p_price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.p_source_id
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private int p_source_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.p_pic
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private String p_pic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.p_actival
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private String p_actival;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.p_license
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private String p_license;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.p_info
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private String p_info;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.p_count
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private int p_count;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.p_address
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private String p_address;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.p_my_num
	 * @return  the value of product.p_my_num
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public String getP_my_num() {
		return p_my_num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.p_my_num
	 * @param p_my_num  the value for product.p_my_num
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_my_num(String p_my_num) {
		this.p_my_num = p_my_num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.p_name
	 * @return  the value of product.p_name
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public String getP_name() {
		return p_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.p_name
	 * @param p_name  the value for product.p_name
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_name(String p_name) {
		this.p_name = p_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.p_abbreviation
	 * @return  the value of product.p_abbreviation
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public String getP_abbreviation() {
		return p_abbreviation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.p_abbreviation
	 * @param p_abbreviation  the value for product.p_abbreviation
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_abbreviation(String p_abbreviation) {
		this.p_abbreviation = p_abbreviation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.p_barcode
	 * @return  the value of product.p_barcode
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public String getP_barcode() {
		return p_barcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.p_barcode
	 * @param p_barcode  the value for product.p_barcode
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_barcode(String p_barcode) {
		this.p_barcode = p_barcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.p_unit
	 * @return  the value of product.p_unit
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public String getP_unit() {
		return p_unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.p_unit
	 * @param p_unit  the value for product.p_unit
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_unit(String p_unit) {
		this.p_unit = p_unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.p_size
	 * @return  the value of product.p_size
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public String getP_size() {
		return p_size;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.p_size
	 * @param p_size  the value for product.p_size
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_size(String p_size) {
		this.p_size = p_size;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.p_class_id
	 * @return  the value of product.p_class_id
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public int getP_class_id() {
		return p_class_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.p_class_id
	 * @param p_class_id  the value for product.p_class_id
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_class_id(int p_class_id) {
		this.p_class_id = p_class_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.p_cost
	 * @return  the value of product.p_cost
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public double getP_cost() {
		return p_cost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.p_cost
	 * @param p_cost  the value for product.p_cost
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_cost(double p_cost) {
		this.p_cost = p_cost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.p_price
	 * @return  the value of product.p_price
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public double getP_price() {
		return p_price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.p_price
	 * @param p_price  the value for product.p_price
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_price(double p_price) {
		this.p_price = p_price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.p_source_id
	 * @return  the value of product.p_source_id
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public int getP_source_id() {
		return p_source_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.p_source_id
	 * @param p_source_id  the value for product.p_source_id
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_source_id(int p_source_id) {
		this.p_source_id = p_source_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.p_pic
	 * @return  the value of product.p_pic
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public String getP_pic() {
		return p_pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.p_pic
	 * @param p_pic  the value for product.p_pic
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_pic(String p_pic) {
		this.p_pic = p_pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.p_actival
	 * @return  the value of product.p_actival
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public String getP_actival() {
		return p_actival;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.p_actival
	 * @param p_actival  the value for product.p_actival
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_actival(String p_actival) {
		this.p_actival = p_actival;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.p_license
	 * @return  the value of product.p_license
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public String getP_license() {
		return p_license;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.p_license
	 * @param p_license  the value for product.p_license
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_license(String p_license) {
		this.p_license = p_license;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.p_info
	 * @return  the value of product.p_info
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public String getP_info() {
		return p_info;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.p_info
	 * @param p_info  the value for product.p_info
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_info(String p_info) {
		this.p_info = p_info;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.p_count
	 * @return  the value of product.p_count
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public int getP_count() {
		return p_count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.p_count
	 * @param p_count  the value for product.p_count
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_count(int p_count) {
		this.p_count = p_count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.p_address
	 * @return  the value of product.p_address
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public String getP_address() {
		return p_address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.p_address
	 * @param p_address  the value for product.p_address
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setP_address(String p_address) {
		this.p_address = p_address;
	}


}