package com.beibei.erp.bean;

import java.util.Date;
import java.util.List;

public class Purchase {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase.pk
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private Integer pk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase.purchase_id
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private String purchase_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase.signer
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private String signer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase.create_date
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private Date create_date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase.total
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	private int total;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase.pk
	 * @return  the value of purchase.pk
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public Integer getPk() {
		return pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase.pk
	 * @param pk  the value for purchase.pk
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setPk(Integer pk) {
		this.pk = pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase.purchase_id
	 * @return  the value of purchase.purchase_id
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public String getPurchase_id() {
		return purchase_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase.purchase_id
	 * @param purchase_id  the value for purchase.purchase_id
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setPurchase_id(String purchase_id) {
		this.purchase_id = purchase_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase.signer
	 * @return  the value of purchase.signer
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public String getSigner() {
		return signer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase.signer
	 * @param signer  the value for purchase.signer
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setSigner(String signer) {
		this.signer = signer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase.create_date
	 * @return  the value of purchase.create_date
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public Date getCreate_date() {
		return create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase.create_date
	 * @param create_date  the value for purchase.create_date
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setCreate_date(Date create_date) {
		this.create_date = create_date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase.total
	 * @return  the value of purchase.total
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public int getTotal() {
		return total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase.total
	 * @param total  the value for purchase.total
	 * @mbggenerated  Mon Jun 15 22:50:26 CST 2015
	 */
	public void setTotal(int total) {
		this.total = total;
	}

	private List<PurchaseDetail> purchaseDetailList;

	public List<PurchaseDetail> getPurchaseDetailList() {
		return purchaseDetailList;
	}

	public void setPurchaseDetailList(List<PurchaseDetail> purchaseDetailList) {
		this.purchaseDetailList = purchaseDetailList;
	}
	
	private List<PurchaseDetail> children; //for json

	public List<PurchaseDetail> getChildren() {
		return children;
	}

	public void setChildren(List<PurchaseDetail> children) {
		this.children = children;
	}
	
	private String jsonId;

	public String getJsonId() {
		return jsonId;
	}

	public void setJsonId(String jsonId) {
		this.jsonId = jsonId;
	}
	
	
	//
	private String createDate;

	public String getCreateDate() {
		return createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}
	
	
	
	
	
	
}