package com.beibei.erp.bean;

public class PurchaseDetailKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase_detail.purchase_id
	 * @mbggenerated  Wed Jun 03 22:43:53 CST 2015
	 */
	private String purchase_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase_detail.p_id
	 * @mbggenerated  Wed Jun 03 22:43:53 CST 2015
	 */
	private int p_id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase_detail.purchase_id
	 * @return  the value of purchase_detail.purchase_id
	 * @mbggenerated  Wed Jun 03 22:43:53 CST 2015
	 */
	public String getPurchase_id() {
		return purchase_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase_detail.purchase_id
	 * @param purchase_id  the value for purchase_detail.purchase_id
	 * @mbggenerated  Wed Jun 03 22:43:53 CST 2015
	 */
	public void setPurchase_id(String purchase_id) {
		this.purchase_id = purchase_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase_detail.p_id
	 * @return  the value of purchase_detail.p_id
	 * @mbggenerated  Wed Jun 03 22:43:53 CST 2015
	 */
	public int getP_id() {
		return p_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase_detail.p_id
	 * @param p_id  the value for purchase_detail.p_id
	 * @mbggenerated  Wed Jun 03 22:43:53 CST 2015
	 */
	public void setP_id(int p_id) {
		this.p_id = p_id;
	}
}