package com.beibei.erp.bean;

public class PurchaseDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase_detail.pk
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	private Integer pk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase_detail.purchase_id
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	private String purchase_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase_detail.p_id
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	private int p_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase_detail.p_count_in
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	private int p_count_in;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase_detail.p_price
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	private int p_price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase_detail.p_source_id
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	private int p_source_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column purchase_detail.supplier_id
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	private String supplier_id;



	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase_detail.pk
	 * @return  the value of purchase_detail.pk
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public Integer getPk() {
		return pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase_detail.pk
	 * @param pk  the value for purchase_detail.pk
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public void setPk(Integer pk) {
		this.pk = pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase_detail.purchase_id
	 * @return  the value of purchase_detail.purchase_id
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public String getPurchase_id() {
		return purchase_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase_detail.purchase_id
	 * @param purchase_id  the value for purchase_detail.purchase_id
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public void setPurchase_id(String purchase_id) {
		this.purchase_id = purchase_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase_detail.p_id
	 * @return  the value of purchase_detail.p_id
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public int getP_id() {
		return p_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase_detail.p_id
	 * @param p_id  the value for purchase_detail.p_id
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public void setP_id(int p_id) {
		this.p_id = p_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase_detail.p_count_in
	 * @return  the value of purchase_detail.p_count_in
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public int getP_count_in() {
		return p_count_in;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase_detail.p_count_in
	 * @param p_count_in  the value for purchase_detail.p_count_in
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public void setP_count_in(int p_count_in) {
		this.p_count_in = p_count_in;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase_detail.p_price
	 * @return  the value of purchase_detail.p_price
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public int getP_price() {
		return p_price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase_detail.p_price
	 * @param p_price  the value for purchase_detail.p_price
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public void setP_price(int p_price) {
		this.p_price = p_price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase_detail.p_source_id
	 * @return  the value of purchase_detail.p_source_id
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public int getP_source_id() {
		return p_source_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase_detail.p_source_id
	 * @param p_source_id  the value for purchase_detail.p_source_id
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public void setP_source_id(int p_source_id) {
		this.p_source_id = p_source_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column purchase_detail.supplier_id
	 * @return  the value of purchase_detail.supplier_id
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public String getSupplier_id() {
		return supplier_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column purchase_detail.supplier_id
	 * @param supplier_id  the value for purchase_detail.supplier_id
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public void setSupplier_id(String supplier_id) {
		this.supplier_id = supplier_id;
	}

	//for json
	private String p_num;
	private String p_name;
	private String jsonId;
	
	

	public String getJsonId() {
		return jsonId;
	}

	public void setJsonId(String jsonId) {
		this.jsonId = jsonId;
	}

	public String getP_num() {
		return p_num;
	}

	public void setP_num(String p_num) {
		this.p_num = p_num;
	}

	public String getP_name() {
		return p_name;
	}

	public void setP_name(String p_name) {
		this.p_name = p_name;
	}
	
	
	
}