package com.beibei.erp.bean;

public class Supplier {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supplier.pk
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	private Integer pk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supplier.supplier_id
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	private String supplier_id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supplier.supplier_name
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	private String supplier_name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supplier.supplier_phone
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	private String supplier_phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column supplier.supplier_contact
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	private String supplier_contact;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supplier.pk
	 * @return  the value of supplier.pk
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public Integer getPk() {
		return pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supplier.pk
	 * @param pk  the value for supplier.pk
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public void setPk(Integer pk) {
		this.pk = pk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supplier.supplier_id
	 * @return  the value of supplier.supplier_id
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public String getSupplier_id() {
		return supplier_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supplier.supplier_id
	 * @param supplier_id  the value for supplier.supplier_id
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public void setSupplier_id(String supplier_id) {
		this.supplier_id = supplier_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supplier.supplier_name
	 * @return  the value of supplier.supplier_name
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public String getSupplier_name() {
		return supplier_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supplier.supplier_name
	 * @param supplier_name  the value for supplier.supplier_name
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public void setSupplier_name(String supplier_name) {
		this.supplier_name = supplier_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supplier.supplier_phone
	 * @return  the value of supplier.supplier_phone
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public String getSupplier_phone() {
		return supplier_phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supplier.supplier_phone
	 * @param supplier_phone  the value for supplier.supplier_phone
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public void setSupplier_phone(String supplier_phone) {
		this.supplier_phone = supplier_phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column supplier.supplier_contact
	 * @return  the value of supplier.supplier_contact
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public String getSupplier_contact() {
		return supplier_contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column supplier.supplier_contact
	 * @param supplier_contact  the value for supplier.supplier_contact
	 * @mbggenerated  Thu Jul 02 23:41:39 CST 2015
	 */
	public void setSupplier_contact(String supplier_contact) {
		this.supplier_contact = supplier_contact;
	}
}